apiVersion: v1
kind: Service
metadata:
  name: frontend-internal
  labels:
    app: guestbook
    tier: frontend
    version: v1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
    version: v1
